#!/usr/bin/env bash
# must be runned with root privileges

# I stopped backuping as i can revert my changes from git tree
#function backup {
#	mkdir $INSTALL_PATH/backup
#	mv $INSTALL_PATH/*nix $INSTALL_PATH/backup
#}

function installConfiguration {
#	backup
	rm -rf $INSTALL_PATH/*
	cp -a * $INSTALL_PATH/
	rm $INSTALL_PATH/{LICENSE,README.md,install,update}
}

pushd /home/musfay/nixos-config
if [ -f "/mnt/etc/nixos/configuration.nix" -a -f "/mnt/etc/nixos/hardware-configuration.nix" ]; then
	INSTALL_PATH=/mnt/etc/nixos
	installConfiguration
	# regenerate hardware-config
	nixos-generate-config --root /mnt
	# add home-manager channel
	nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
	nix-channel --update
	# install
	nixos-install
	echo "     Installation finished!"
else
	INSTALL_PATH=/etc/nixos
	installConfiguration
	# regenerate hardware-config
	nixos-generate-config --root /
fi
popd

