#!/usr/bin/env bash

# DROPPED
# I used to first edit my changes on /etc and copy them into my repo.
# Now I'm making my changes in my repo first and applying those changes to my system
# with install script.

REPODIR=$HOME/nixos-config
INPUT=$1

if [ -n "$INPUT" ]; then
	COMMIT_MESSAGE="$INPUT"
else
	COMMIT_MESSAGE="update"
fi

function update() {
	rm -f *.nix
	cp -a /etc/nixos/* ./
	rm hardware-configuration.nix
}

function commit() {
	git pull
	git add *
	git commit -m "$COMMIT_MESSAGE"
	git push
}

pushd $REPODIR
update
commit
popd
